### ISSUE TITLE
Latest SF2 release needs a tag

### ISSUE THREAD

**Issue by uffejakobsen** [Chordian/sidfactory2#101]
Latest SF2 release needs a tag

Whenever you make an (official) release - please make a tag (here on github)

That enables packagers for linux distributions to easily have a fixed point to base their packages on (other than SHA)

/Uffe :-)

**Comment by micheldebree** [comment]
Hi Uffe, thanks for reporting this. I forgot to make a tag, but it's here now:

https://github.com/Chordian/sidfactory2/releases/tag/release-20210104
