### ISSUE TITLE
Support configuration of favorite folders

### ISSUE THREAD

**Issue by micheldebree** [Chordian/sidfactory2#125]
**Is your feature request related to a problem? Please describe.**
I need to manually navigate to my favorite folder(s) to load and save sf2 files.

**Describe the solution you'd like**
Configure a list of my favorite folders so I can open them directly from the file dialog

**Describe alternatives you've considered**

**Additional context**

**Comment by micheldebree** [comment]
Some default folders are hard coded now for macOS and linux. They can be removed and added as favorites in the os-specific sections of config.ini

**Comment by micheldebree** [comment]
Also added Disk.Startup.Folder to configure the startup folder for the disk browser.

**Comment by Chordian** [comment]
Tested and confirmed that it works.
