### ISSUE TITLE
Merge the converter into the editor source codes

### ISSUE THREAD

**Issue by Chordian** [Chordian/sidfactory2#13]
A big one. All source code for the converter should be merged into the editor solution, abandoning the use of a console.

Instead, loading with **F10** should automatically try to detect the file format. If it's an SF2 source file, it loads that as usual. If not, it detects whether it's something that can be imported. If it is and it's converted without the need for outputting messages, it will feel the same as if you loaded an SF2 source file.

If messages are needed to be shown, a box pops up. If just notes and warnings, you may edit the tune when closing it. If errors, the tune is not loaded as you close the box.

**Comment by Chordian** [comment]
_This is a task migrated from workstreams in Slack._

**Comment by micheldebree** [comment]
Will there be some dialog for instance to choose which 3 voices to use from a 4 channel mod?

**Comment by Chordian** [comment]
There could be a dialog box options that appears depending on the source file format, e.g. to select what voice to exclude. Might be a nice thing to have.
