### ISSUE TITLE
size_t definition missing in picopng library header

### ISSUE THREAD

**Issue by jansalleine** [Chordian/sidfactory2#134]
Hi,

when compiling on linux I got tons of errors because of size_t not being declared in picopng library.

Including cstddef in picopng.h will fix this:
```
#pragma once

#include <vector>
#include <cstddef>

namespace PicoPNG
{
	int decodePNG(std::vector<unsigned char>& out_image, unsigned long& image_width, unsigned long& image_height, const unsigned char* in_png, size_t in_size, bool convert_to_rgba32);
}
```

**Comment by micheldebree** [comment]
Hi there, what version of Linux are you compiling on?
What are the steps you use to compile? 
I am asking because our reference linux build is succeeding for the master branch, so it does work on some linuxes. 
Thanks for reporting!

**Comment by micheldebree** [comment]
P.S. picopng is an external dependency so I would prefer to not change anything in the source code for picopng.

**Comment by jansalleine** [comment]
I'm using Arch Linux with gcc 11.1.0. Steps to compile: "make" :-)
After asking google: I think older versions of gcc weren't so picky about missing standard headers.

**Comment by micheldebree** [comment]
I did the suggested fix on the bug/134 branch: https://github.com/Chordian/sidfactory2/tree/bug/134
@jansalleine Could you confirm this fixes the issue?

**Comment by jansalleine** [comment]
@micheldebree Yes, current head -> master of SF2 compiles fine now on Arch / gcc 11.1.0.
