### ISSUE TITLE
Tag for release 20211230 is missing

### ISSUE THREAD

**Issue by uffejakobsen** [Chordian/sidfactory2#155]
Repeating the request from issue #101 

Latest SF2 release needs a tag

Whenever you make an (official) release - please make a tag (here on github)

That enables packagers for linux distributions to easily have a fixed point to base their packages on (other than SHA)

**Comment by micheldebree** [comment]
Hi @uffejakobsen, like in #101 I forgot again, sorry. I will make a checklist for releasing so we don't forget again.

The tag is https://github.com/Chordian/sidfactory2/releases/tag/release-20211230

Do you know of any linux packages for SF2? We could document how to install on different distro's if packages are being maintained for those.

**Comment by uffejakobsen** [comment]
> 
> The tag is https://github.com/Chordian/sidfactory2/releases/tag/release-20211230
Thanks :-) :+1: 

> 
> Do you know of any linux packages for SF2? We could document how to install on different distro's if packages are being maintained for those.

@micheldebree 
I'm maintaining two sidfactory AUR packages for Archlinux - AUR packages are not exactly a part of the official binary distribution.
The user have to perform the actual build locally

I maintain a stable release package:
https://aur.archlinux.org/packages/sidfactory2/

And a bleeding edge (from master) (unstable) package:
https://aur.archlinux.org/packages/sidfactory2-git/

I will update the stable package to the new release over the weekend :-)

**Comment by micheldebree** [comment]
Ok good to know. We aim to keep the master branch stable by the way, personally I always try to use the master branch for making music. Do you think it is useful for archlinux users to add a few lines to the readme on how to install?

**Comment by uffejakobsen** [comment]
>  Do you think it is useful for archlinux users to add a few lines to the readme on how to install?
Well, the AUR pkgbuild provided by me will build a native Archlinux package that will automatically be installed by the package manager - just like any other binary package for that distribution.

The problem with SF2 is that it violates the established filesystem layout dictated by most linux'es.

As an example the old SF2 20210104 expects that the drivers dubdir is found in the same dir as the sf2 binary... that is not really allowed by most linux distros

For the old SF2 release I had to do a lot of tweaks to make it work - while still maintaining the filesystem layout dictated by most linux'es...

I've been wanting to write to you about that - but just never got around to do it...

I have to take a look at the new release to see how much of this have changed... :-)
