### ISSUE TITLE
Quick save warning toggle - OR - remove quick save warning altogether

### ISSUE THREAD

**Issue by Chordian** [Chordian/sidfactory2#16]
Suggesting two ways to do this:

<img width="632" alt="quicksave_checkbox" src="https://user-images.githubusercontent.com/16590737/92993464-12080580-f4f2-11ea-900d-f040392302fe.png">

1. A check box in a dialog box. When ticked and accepting, the warning dialog never appears again. (That song only or forever? Not sure.)
2. Don't change the dialog box but instead introduce the new `SaveWarning: ON` top banner option. When `OFF` the top header should write `Saved` for a second when quick saving. As an extra security measure, the warning is always `ON` when starting SF2 so that you're always conscious about turning it off.

**Comment by Chordian** [comment]
_This is a task migrated from workstreams in Slack._

**Comment by Chordian** [comment]
I think, maybe, I prefer the second idea myself, but the top banner doesn't have unlimited space for options like that.

**Comment by micheldebree** [comment]
I think the normal behaviour in other software is to just overwrite the file. Having a setting to worry about makes it more complicated. In other software I know to first do a save as.. if I want to keep the original before changing things.
The setting would protect the user against unintentional overwrite of the original. But if it can be toggled on and off it is still not really protecting me when I mindlessly press CTRL-S without checking the setting first.
So I have my doubts if we need the setting at all ;)

Could this be combined with some sort of automatic backup, or more direct 'save as new version' or something?

**Comment by Chordian** [comment]
I actually agree. I've never quite understood why quick save needs a confirmation dialog in the first place.
