### ISSUE TITLE
Include official linux distribution

### ISSUE THREAD

**Issue by micheldebree** [Chordian/sidfactory2#3]
Just a zip file with
- [x] A binary
- [x] The resources
- [ ] Instructions for installation

TODO:
- [x] Include sf2converter
- [x] Fix loading of default resources

The source should also have instructions on how to build it yourself.
When unzipped, the resources should be found relatively to the executable.
The sf2 framework should be installed seperately -> refer to sf2 site in the instructions

Before releasing, put it in the CSDB forum to see if it works as expected for real Linux users and gather feedback.

Out of scope:
- In general, distro dependent stuff like:
- fancy installer packages
- inclusion in public package manager repositories

**Comment by micheldebree** [comment]
> The linux build seems to work in Ubuntu, except for the loading of resources:
> 
> - no default driver loaded
> 
> - no switching colorschemes
> 
> - no overlays

This is fixed now. Merged into master. No official build yet until we know the key binding is ok

**Comment by uffejakobsen** [comment]
FYI: ArchLinux AUR package is available here https://aur.archlinux.org/packages/sidfactory2/
