### ISSUE TITLE
Undo crashes when saved as new song

### ISSUE THREAD

**Issue by Chordian** [Chordian/sidfactory2#51]
@micheldebree:

> On macOS:
> 
> * Open a song
> * Edit something (I changed a value in the instrument table)
> * Save under a different name with **F11**
> * Undo = Crash
> 
> I guess saving it as a new song messes up the undo history.

**Comment by Chordian** [comment]
_This is a task migrated from workstreams in Slack._

**Comment by micheldebree** [comment]
Could not reproduce, think @TheRealLaxity fixed this once. Undo doesn't work after save-new-file, but doesn't crash.
