### ISSUE TITLE
Sound processing is skipped on the note off events

### ISSUE THREAD

**Issue by Chordian** [Chordian/sidfactory2#54]
This is an old task imported from a `notes.txt` file as a known issue. It wasn't designated a specific driver version.

**Comment by Chordian** [comment]
_This is a task migrated from workstreams in Slack._

**Comment by Chordian** [comment]
Is this still a problem?

**Comment by TheRealLaxity** [comment]
I think we should close this one. I'm not sure what it means, and what driver this is referring to.
