### ISSUE TITLE
Support overlays and color schemes

### ISSUE THREAD

**Issue by Chordian** [Chordian/sidfactory2#57]
@micheldebree:

> Overlays and color schemes should be bundled in the .app so they can be used right away. Custom overlays and color schemes support is handled in #58.
> 
> * Package color schemes and overlays in the .app
> * Set the right default paths

**Comment by Chordian** [comment]
_This is a task migrated from workstreams in Slack._

**Comment by micheldebree** [comment]
Done in the latest release

**Comment by Tekl** [comment]
How can I select a color scheme in the user.ini? Is there a key/value for it?

**Comment by Chordian** [comment]
Yes. Open _config.ini_ in the SF2 folder and look up "ColorScheme.Selection" in it. The comments for that entry will tell you what you need to do.
