### ISSUE TITLE
In resize dialog, display sequence number that is being edited

### ISSUE THREAD

**Issue by SCWinde** [Chordian/sidfactory2#78]
There's room left, so make that "Enter size of sequence [INSERT SEQ NUMBER]":

<img width="332" alt="Schermafbeelding 2020-10-15 om 21 46 47" src="https://user-images.githubusercontent.com/45142938/96180207-6445a780-0f32-11eb-91f1-da673de52d02.png">

**Comment by Chordian** [comment]
Sure, an easy and logical change: `Enter size of sequence #06`

**Comment by TheRealLaxity** [comment]
This is already in the current build!
