### ISSUE TITLE
Loading driver np20 does not change the overlay

### ISSUE THREAD

**Issue by micheldebree** [Chordian/sidfactory2#86]
The overlay does not change to np20 but stays at whatever it was before.

**Comment by Chordian** [comment]
I just added the overlays for Linux and macOS as well. That should fix this bug.

**Comment by Chordian** [comment]
Neither converting by loading a PRG nor loading the NP20 driver directly currently changes the overlay.

**Comment by TheRealLaxity** [comment]
Fixed

**Comment by Chordian** [comment]
It now works fine in Windows.

@micheldebree Do you want to verify this in macOS too?

**Comment by micheldebree** [comment]
Yep this works now.
