### ISSUE TITLE
Final updates to NP20

### ISSUE THREAD

**Issue by Chordian** [Chordian/sidfactory2#87]
There are a few things to do before the NP20 driver is complete.

- Add vibrato feeling
- Make sure meta data tells the hotkey to jump to the correct tables on indices
- Wave index commands
- Tempo command
- Volume command

**Comment by Chordian** [comment]
Anything else missing?

**Comment by TheRealLaxity** [comment]
Fixed meta data
Fixed wave index commands
Fixed volume command

**Comment by micheldebree** [comment]
Do we need documentation in a note file like for the other drivers? Or is the overlay enough?

**Comment by Chordian** [comment]
I lean towards not having a note file for NP20. It's kind of an Easter egg driver, works exactly like the old driver, and is expected to be used by people who already know NP20. Maybe the overlay is enough?

**Comment by Chordian** [comment]
There were a couple of bugs with the tempo command, but @TheRealLaxity has fixed them now. All of the remaining things should now be in NP20 and we can close this issue.
