### ISSUE TITLE
Glitchy behaviour after window loses focus.

### ISSUE THREAD

**Issue by micheldebree** [Chordian/sidfactory2#89]
This reproduces it every time for me:

- CTRL-F2. This sets focus to the system menu on my macOS, causing the SF2 window to lose focus
- ESC. This sets focus back to SF2

By now the cursor keys have stopped working. I can only move the cursor by clicking with the mouse.

- CTRL

Now things start flashing erraticly like broken fluorescent lights. The same behaviour as when I keep F2 pressed all the time. Pressing F2 stops this behaviour.

**Comment by micheldebree** [comment]
This typically happens if you press CTRL-F2 instread of CTRL-2. The quickest way to recover is to press CTRL followed by F2 (**not**) at the same time.

**Comment by micheldebree** [comment]
Logged all the SDL events. There are no window events being received whatsoever when losing focus nor when regaining focus :(

The logging shows or assumption was right:

CTRL+F2 -> logged event 768 with keycode 400000E0 = CTRL *down*

Focus shifted to system menu. 

ESC (while focus is on system menu) -> logged event 768 with keycode 4000003B = F2 *down*

So both the CTRL *up* and F2 *up* are lost. Weird thing is that the F2 *down* event is received after regaining focus, but the F2 *up* that should come after that is lost...

**Comment by micheldebree** [comment]
Probably won't be able to fix. Labeled it 'known issue'.

**Comment by Grrrolf** [comment]
FYI:
ctrl-F2 is a keyboard shortcut on OS level:
![image](https://user-images.githubusercontent.com/10052794/117545926-291ed900-b028-11eb-98f0-38d3fe4cc939.png)
I don't think it's a good idea asking people to turn this off. This makes using other applications less accessible for keyboard navigation.

An alternative could be instead of using ctrl+<key> using cmd+<key> instead on the mac. This is also much more in line with macOS in general.

**Comment by micheldebree** [comment]
The official release builds are built with make, I don't touch xcode at all :) If you build an App bundle, the mapping for "Play from cursor" should be Cmd+F2.

Is your master up-to-date? Until recently there was a wrong mapping in master.

By 'linux style' I mean building with the Makefile in the project root. An app built with the Makefile in /macos should have the Cmd+F2 mapping (Ctrl-F2 is not mapped to anything).

Have you built an App bundle where 'Play from cursor' is not mapped to Cmd+F2?
