### ISSUE TITLE
After packing, can't edit tracks anymore

### ISSUE THREAD

**Issue by hqn-scl** [Chordian/sidfactory2#91]
I packed a tune, wrote to a SID file and returned to the editor.

With any track in focus, the following issue occurs after packing:
1. cursor left/right doesn't work, cursor stays in place in the track
2. cursor up/down scrolls through instrument table instead of track (behaves like CMD-up/down)
3. TAB switches through all tracks/tables/sequences etc as expected, and I can edit these just fine

It's just that tracks remain inoperable after packing until I restart SF2

OS: MacOS 10.15.3
SF2 version: 2020911

**Comment by micheldebree** [comment]
I cannot reproduce this (macOS 10.14.6, SF2 20200911).
@hqn-scl Is there any time in this scenario when focus is lost from the SF2 window? Like a popup from the OS or something? Are there any conflicts in the keybindings with OS functions, like for the F6 key for example?

There is a known issue when keybindings conflict with 'outside' functions that take away focus from SF2. Keys can get stuck from SF2's point of view. Is the behaviour maybe consistent with a stuck key? Maybe one of the control keys like CTRL, SHIFT..?

**Comment by hqn-scl** [comment]
One day later: just went through the same steps with the same tune and the problem seems to have disappeared. As far as I can see there are no keybinding conflicts. I will try to test again with OS popups to see if it makes any difference.

**Comment by micheldebree** [comment]
Thanks. FYI it could be related, or similar to https://github.com/Chordian/sidfactory2/issues/89

**Comment by micheldebree** [comment]
@TheRealLaxity managed to reproduce:

Set follow playmode, start playing, press shift+s to quick save, press yes or no, tracks cannot be edited!
